#Import dependecies

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

##Load the dataset

In [2]:
df = pd.read_csv("Cars_price.csv")

In [3]:
print(df.columns)

Index(['cylinders', ' milage', ' year', ' price'], dtype='object')

#Preprocessing

In [4]:
df.columns = df.columns.str.strip()
print(df.columns)

Index(['cylinders', 'milage', 'year', 'price'], dtype='object')

##Lets add a row

In [5]:
df.loc[5]=[3, 50000, None, 2100000]

In [6]:
df

   cylinders   milage    year      price
0        3.0  30000.0  2024.0  2500000.0
1        4.0  25000.0  2022.0  3100000.0
2        4.0  50000.0  2020.0  2400000.0
3        6.0  30000.0  2023.0  5000000.0
4        8.0  25000.0  2022.0  8000000.0
5        3.0  50000.0     NaN  2100000.0

In [7]:
df.describe()

       cylinders        milage        year         price
count   6.000000      6.000000     5.00000  6.000000e+00
mean    4.666667  35000.000000  2022.20000  3.850000e+06
std     1.966384  11832.159566     1.48324  2.284513e+06
min     3.000000  25000.000000  2020.00000  2.100000e+06
25%     3.250000  26250.000000  2022.00000  2.425000e+06
50%     4.000000  30000.000000  2022.00000  2.800000e+06
75%     5.500000  45000.000000  2023.00000  4.525000e+06
max     8.000000  50000.000000  2024.00000  8.000000e+06

##Handle missing data

In [8]:
mean_year = int(df['year'].mean())
df['year'] = df['year'].fillna(float(mean_year))
df

   cylinders   milage    year      price
0        3.0  30000.0  2024.0  2500000.0
1        4.0  25000.0  2022.0  3100000.0
2        4.0  50000.0  2020.0  2400000.0
3        6.0  30000.0  2023.0  5000000.0
4        8.0  25000.0  2022.0  8000000.0
5        3.0  50000.0  2022.0  2100000.0

#Train the Model

In [9]:
reg = linear_model.LinearRegression()
reg.fit(df[['cylinders', 'milage', 'year']], df.price)

LinearRegression()

#Model Parameters

In [10]:
reg.coef_

array([ 1.12790004e+06, -5.56135770e+00,  2.09623275e+05])

In [11]:
reg.intercept_

np.float64(-425112085.0428948)

In [12]:
reg.predict([[4, 30000, 2021]])

c:\Users\ZEENAT MUSTAFA\.conda\envs\ai-bootcamp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([2881312.94293165])

In [13]:
hiring = pd.read_csv("hiring.csv")
hiring

   experience  test_score  interview_score  salary
0         NaN         8.0                9   50000
1         NaN         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         NaN                7   72000
7        11.0         7.0                8   80000

In [14]:
hiring['experience'].fillna(0, inplace=True)

C:\Users\ZEENAT MUSTAFA\AppData\Local\Temp\ipykernel_19676\3713478144.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  hiring['experience'].fillna(0, inplace=True)

In [15]:
hiring

   experience  test_score  interview_score  salary
0         0.0         8.0                9   50000
1         0.0         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         NaN                7   72000
7        11.0         7.0                8   80000

In [16]:
import math

mean_test = hiring['test_score'].mean()
hiring['test_score'] = hiring.test_score.fillna(math.floor(mean_test))
hiring

   experience  test_score  interview_score  salary
0         0.0         8.0                9   50000
1         0.0         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         7.0                7   72000
7        11.0         7.0                8   80000

In [17]:
reg_hiring = linear_model.LinearRegression()
reg.fit(hiring[['experience', 'test_score','interview_score']], hiring.salary)

LinearRegression()

In [18]:
reg.predict([[2, 9, 6],[12, 10, 10]])

c:\Users\ZEENAT MUSTAFA\.conda\envs\ai-bootcamp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([53713.86677124, 93747.79628651])

In [19]:
import pickle

In [20]:
with open('car_pred_model','wb')as file:
    pickle.dump(reg, file)

In [21]:
with open('car_pred_model','rb') as file:
    mp = pickle.load(file)

mp.predict([[2,9,6]])

c:\Users\ZEENAT MUSTAFA\.conda\envs\ai-bootcamp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([53713.86677124])

#Doing another with a different file which has car models in it.

In [22]:
cars = pd.read_csv('carprices.csv')

In [23]:
cars

                Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [24]:
cars.columns = ['Car_Model', 'Milage', 'Sell_Price', 'Age']
cars

                Car_Model  Milage  Sell_Price  Age
0                  BMW X5   69000       18000    6
1                  BMW X5   35000       34000    3
2                  BMW X5   57000       26100    5
3                  BMW X5   22500       40000    2
4                  BMW X5   46000       31500    4
5                 Audi A5   59000       29400    5
6                 Audi A5   52000       32000    5
7                 Audi A5   72000       19300    6
8                 Audi A5   91000       12000    8
9   Mercedez Benz C class   67000       22000    6
10  Mercedez Benz C class   83000       20000    7
11  Mercedez Benz C class   79000       21000    7
12  Mercedez Benz C class   59000       33000    5

##One‑hot encode the Car_Model column to convert into numerical data for traininng the model.

The model can only be trained on numerical data

In [25]:
dummies = pd.get_dummies(cars.Car_Model)
dummies

    Audi A5  BMW X5  Mercedez Benz C class
0     False    True                  False
1     False    True                  False
2     False    True                  False
3     False    True                  False
4     False    True                  False
5      True   False                  False
6      True   False                  False
7      True   False                  False
8      True   False                  False
9     False   False                   True
10    False   False                   True
11    False   False                   True
12    False   False                   True

In [26]:
dum_cars = pd.concat([cars,dummies], axis = 'columns')
dum_cars

,Car_Model,Milage,Sell_Price,Age,Audi A5,BMW X5,Mercedez Benz C class
0,BMW X5,69000,18000,6,False,True,False
1,BMW X5,35000,34000,3,False,True,False
2,BMW X5,57000,26100,5,False,True,False
3,BMW X5,22500,40000,2,False,True,False
4,BMW X5,46000,31500,4,False,True,False
5,Audi A5,59000,29400,5,True,False,False
6,Audi A5,52000,32000,5,True,False,False
7,Audi A5,72000,19300,6,True,False,False
8,Audi A5,91000,12000,8,True,False,False
9,Mercedez Benz C class,67000,22000,6,False,False,True
10,Mercedez Benz C class,83000,20000,7,False,False,True
11,Mercedez Benz C class,79000,21000,7,False,False,True
12,Mercedez Benz C class,59000,33000,5,False,False,True

In [27]:
dum_cars.rename(columns={'Mercedez Benz C class': 'Mercedes_C_class'}, inplace=True)

In [28]:
dum_cars

,Car_Model,Milage,Sell_Price,Age,Audi A5,BMW X5,Mercedes_C_class
0,BMW X5,69000,18000,6,False,True,False
1,BMW X5,35000,34000,3,False,True,False
2,BMW X5,57000,26100,5,False,True,False
3,BMW X5,22500,40000,2,False,True,False
4,BMW X5,46000,31500,4,False,True,False
5,Audi A5,59000,29400,5,True,False,False
6,Audi A5,52000,32000,5,True,False,False
7,Audi A5,72000,19300,6,True,False,False
8,Audi A5,91000,12000,8,True,False,False
9,Mercedez Benz C class,67000,22000,6,False,False,True
10,Mercedez Benz C class,83000,20000,7,False,False,True
11,Mercedez Benz C class,79000,21000,7,False,False,True
12,Mercedez Benz C class,59000,33000,5,False,False,True

##Drop the contextual column

In [29]:
dum_cars = dum_cars.drop('Car_Model', axis='columns')

In [30]:
l_model = linear_model.LinearRegression()

In [31]:
y = cars.Sell_Price
print(y)
X = dum_cars.drop('Sell_Price', axis = 'columns')
X

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell_Price, dtype: int64

    Milage  Age  Audi A5  BMW X5  Mercedes_C_class
0    69000    6    False    True             False
1    35000    3    False    True             False
2    57000    5    False    True             False
3    22500    2    False    True             False
4    46000    4    False    True             False
5    59000    5     True   False             False
6    52000    5     True   False             False
7    72000    6     True   False             False
8    91000    8     True   False             False
9    67000    6    False   False              True
10   83000    7    False   False              True
11   79000    7    False   False              True
12   59000    5    False   False              True

#Now train this data on linear regression and predict price for 45000 milage,4 years old Mercedes C class and 86000 milage, 7 years old Audi A5

In [33]:
#Code here

X = dum_cars.drop(['Sell_Price', 'Mercedes_C_class'], axis='columns')
y = dum_cars.Sell_Price

# Train the model
l_model.fit(X, y)

print(X.columns)

price_mercedes = l_model.predict([[45000, 4, 0, 0]])
print("Predicted price (Mercedes C class, 45000 miles, 4 yrs):", price_mercedes)

price_audi = l_model.predict([[86000, 7, 1, 0]])
print("Predicted price (Audi A5, 86000 miles, 7 yrs):", price_audi)

Index(['Milage', 'Age', 'Audi A5', 'BMW X5'], dtype='object')
Predicted price (Mercedes C class, 45000 miles, 4 yrs): [36991.31721061]
Predicted price (Audi A5, 86000 miles, 7 yrs): [15365.40972059]

c:\Users\ZEENAT MUSTAFA\.conda\envs\ai-bootcamp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
c:\Users\ZEENAT MUSTAFA\.conda\envs\ai-bootcamp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(