## <font color="maroon"><h4 align="center">Handling Missing Data - replace method</font>

In [56]:
import pandas as pd
import numpy as np
df = pd.read_csv("weather_data.csv")
df

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017       -99999          7     Sunny
2  1/3/2017           28     -99999      Snow
3  1/4/2017           24          7      Snow
4  1/5/2017       -99999          4  no event
5  1/6/2017           31          2     Sunny

**Replacing single value**

In [57]:
new_df = df.replace(-99999, value=np.nan)
new_df

        day  temperature  windspeed     event
0  1/1/2017         32.0        6.0      Rain
1  1/2/2017          NaN        7.0     Sunny
2  1/3/2017         28.0        NaN      Snow
3  1/4/2017         24.0        7.0      Snow
4  1/5/2017          NaN        4.0  no event
5  1/6/2017         31.0        2.0     Sunny

**Replacing list with single value**

In [58]:
new_df = df.replace(to_replace=[-99999, -88888], value=0)
new_df

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017            0          7     Sunny
2  1/3/2017           28          0      Snow
3  1/4/2017           24          7      Snow
4  1/5/2017            0          4  no event
5  1/6/2017           31          2     Sunny

**Replacing per column**

In [59]:
new_df = df.replace({
        'temperature': -99999,
        'windspeed': -99999,
        'event': '0'
    }, np.nan)
new_df

        day  temperature  windspeed     event
0  1/1/2017         32.0        6.0      Rain
1  1/2/2017          NaN        7.0     Sunny
2  1/3/2017         28.0        NaN      Snow
3  1/4/2017         24.0        7.0      Snow
4  1/5/2017          NaN        4.0  no event
5  1/6/2017         31.0        2.0     Sunny

**Replacing by using mapping**

In [60]:
new_df = df.replace({
        -99999: np.nan,
        'no event': 'Sunny',
    })
new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017         24.0        7.0   Snow
4  1/5/2017          NaN        4.0  Sunny
5  1/6/2017         31.0        2.0  Sunny

**Regex**

In [61]:
# when windspeed is 6 mph, 7 mph etc. & temperature is 32 F, 28 F etc.
# new_df = df.replace({'temperature': '[A-Za-z]', 'windspeed': '[a-z]'},'', regex=True)

# new_df = df.replace({'temperature': '[A-Za-z]', 'windspeed': '[a-z]'},'', regex=True)

new_df = df.replace({'temperature': '[A-Za-z]', 'windspeed': '[a-z]', -99999: np.nan, 'no event': 'Sunny'}, regex=True)
new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017         24.0        7.0   Snow
4  1/5/2017          NaN        4.0  Sunny
5  1/6/2017         31.0        2.0  Sunny

**Replacing list with another list**

In [62]:
df3 = pd.DataFrame({
    'score': ['exceptional', 'average', 'good', 'poor', 'average', 'exceptional'],
    'student': ['rob', 'maya', 'parthiv', 'tom', 'julian', 'erica']
})
df3

         score  student
0  exceptional      rob
1      average     maya
2         good  parthiv
3         poor      tom
4      average   julian
5  exceptional    erica

In [66]:
#Write the code to replace score from strings to numeric, say poor:1, average:2, good: 3, exceptional: 4

df3.score = df3.score.replace({
    'exceptional': '4',
    'average': '3',
    'good': '2',
    'poor': '1'
})
df3

  score  student
0     4      rob
1     3     maya
2     2  parthiv
3     1      tom
4     3   julian
5     4    erica

In [65]:
df3.replace(['poor', 'average', 'good', 'exceptional'], [1,2,3,4])
df3

  score  student
0     4      rob
1     3     maya
2     2  parthiv
3     1      tom
4     3   julian
5     4    erica